version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:3000

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
      MONGO_NAEM: "uptimeMon"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
