version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: ./frontend
    ports:
      - 4000:3000

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"


volumes:
  mongodb_data:
