version: "3.8"

services:
  next-app:
    container_name: next-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - API_URL=http://api-service:8000 # update to your actually backend ip
    ports:
      - 4000:3000

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  mongodb_data:
